---
- name: Install requirements
  apt:
    name: "{{ debian_requirements }}"

- name: Add Docker's official GPG key
  get_url:
    url: https://download.docker.com/linux/debian/gpg
    dest: /usr/share/keyrings/docker.asc
    owner: root
    group: root
    mode: "0644"

- name: Add the repository to apt sources
  apt_repository:
    repo: deb [arch=amd64 signed-by=/usr/share/keyrings/docker.asc] https://download.docker.com/linux/debian {{ ansible_distribution_release }} stable
    state: present
    filename: docker

- name: Install the Docker packages
  apt:
    name: "{{ docker_packages }}"

- name: Ensure Docker is started and enabled at boot
  systemd:
    name: docker
    state: started
    enabled: true
