---
- name: Get docker-compose checksum
  get_url:
    url: https://github.com/docker/compose/releases/download/v{{ docker_compose_version }}/docker-compose-{{ ansible_system }}-{{ (ansible_architecture == 'x86_64') | ternary('amd64', 'unsupported') }}.sha256
    dest: /tmp/docker_compose_checksum
    force: true

- name: Get sha256sum from docker-compose checksum file
  slurp:
    src: /tmp/docker_compose_checksum
  register: docker_compose_checksum_encoded

- name: Decode docker_compose_checksum_encoded
  set_fact:
    docker_compose_checksum: '{{ docker_compose_checksum_encoded["content"] | b64decode }}'

- name: Make sure old docker-compose (< 2.0.0) is not available
  file:
    src: /usr/local/bin/docker-compose
    state: absent

- name: Install docker-compose
  get_url:
    url: https://github.com/docker/compose/releases/download/v{{ docker_compose_version }}/docker-compose-{{ ansible_system }}-{{ (ansible_architecture == 'x86_64') | ternary('amd64', 'unsupported') }}
    dest: /usr/lib/docker/cli-plugins/docker-compose
    mode: '0755'
    owner: root
    group: root
    checksum: 'sha256:{{ docker_compose_checksum.split(" ")[0] }}'
    force: true
