---
- name: Add docker-ce repo
  get_url:
    url: https://download.docker.com/linux/fedora/docker-ce.repo
    dest: /etc/yum.repos.d/docker-ce.repo
    mode: '0644'
    owner: root
    group: root

- name: Ensure python3-libdnf5 is present
  command: dnf install python3-libdnf5 -y
  register: python3_libdnf5_command_install
  changed_when: "'Nothing to do.' not in python3_libdnf5_command_install.stdout_lines"

- name: Install docker-ce
  dnf:
    name: "{{ docker_packages }}"
  notify:
    - enable docker
    - start docker
