---
- name: Install requirements
  apt:
    name: "{{ debian_requirements }}"

- name: Remove legacy docker-ce repository list
  file:
    path: /etc/apt/sources.list.d/download_docker_com_linux_ubuntu.list
    state: absent

- name: Add docker-ce repository
  deb822_repository:
    name: docker
    types: deb
    uris: https://download.docker.com/linux/ubuntu
    suites: '{{ ansible_facts["distribution_release"] }}'
    components: stable
    architectures: amd64
    signed_by: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: Install docker-ce
  apt:
    name: "{{ docker_packages }}"
    update_cache: true
  notify:
    - enable docker
    - start docker
