---
name: CI
'on':
  pull_request:
  push:
    branches:
      - master
  schedule:
    - cron: '0 0 * * *'

defaults:
  run:
    working-directory: 'aminvakil.docker_installation'

jobs:

  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Check out the codebase.
        uses: actions/checkout@v2
        with:
          path: 'aminvakil.docker_installation'

      - name: Set up Python 3.
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install test dependencies.
        run: pip3 install yamllint ansible-core ansible-lint --pre

      - name: Lint code.
        run: |
          yamllint .
          ansible-lint .

  molecule:
    name: Molecule
    runs-on: ubuntu-latest
    strategy:
      matrix:
        docker_compose: [false, true]
        distro:
          - rockylinux8
          - centos8
          - centos7
          - debian10
          - debian11
          - ubuntu20.04
          - ubuntu18.04
          - ubuntu16.04
          - fedora35
          - fedora34
          - fedora33

    steps:
      - name: Check out the codebase.
        uses: actions/checkout@v2
        with:
          path: 'aminvakil.docker_installation'

      - name: Set up Python 3.
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install test dependencies.
        run: pip3 install ansible molecule[docker] docker --pre

      - name: Run Molecule tests.
        run: molecule test
        env:
          PY_COLORS: '1'
          ANSIBLE_FORCE_COLOR: '1'
          MOLECULE_DISTRO: ${{ matrix.distro }}
          DOCKER_COMPOSE: ${{ matrix.docker_compose }}

  deploy:
    if: github.ref == 'refs/heads/master' && github.event_name == 'push'
    needs: [lint, molecule]
    name: Push to Galaxy
    runs-on: ubuntu-latest
    steps:
      - name: Check out the codebase.
        uses: actions/checkout@v2
        with:
          path: 'aminvakil.docker_installation'

      - name: Set up Python 3.
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install ansible-core.
        run: pip3 install ansible-core

      - name: Push to Ansible Galaxy.
        run: ansible-galaxy role import --token ${{ secrets.GALAXY_API_KEY }} $(echo $GITHUB_REPOSITORY | cut -d/ -f1) $(echo $GITHUB_REPOSITORY | cut -d/ -f2)
